services:
  webapi:
    image: mvilla/finnetflask:latest
    restart: unless-stopped
    environment:
      - env=${env}
      - Tunning=${Tunning}
      - debug=${debug}
      - exturl=${exturl}
      - client=${client}
      - intmode=${intmode}
      - device_id=${device_id}
    volumes:
      - "./webapi:/var/www/flask"
    networks:
      internal-network:
        aliases:
          - ${env}
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 1G
      mode: replicated
      replicas: 3
  webapp:
    image: mvilla/finnetflask:latest
    restart: unless-stopped
    environment:
      - env=${env}
    ports:
      - "80:5000"
    volumes:
      - "./webapp:/var/www/flask"
      - "/data:/data"
    networks:
      - internal-network
      - external-network
    deploy:
      mode: replicated
      replicas: 1

networks:
  internal-network:
    internal: true
  external-network:
